services:
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    volumes:
      - ./allure-results:/app/allure-results
    command: >
      sh -c "rm -rf /app/allure-results/* &&
             pytest -v -n auto --reruns=1 --alluredir=/app/allure-results"
