name: Pytest Playwright tests

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and Run Tests in Docker
      run: docker compose up --abort-on-container-exit --exit-code-from tests

    - name: Tear down containers
      if: always()
      run: docker compose down

    - name: Upload Allure results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results

    - name: Install Allure CLI
      if: always()
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        curl -Ls https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz -o allure.tgz
        sudo tar -zxvf allure.tgz -C /opt/
        sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
        allure --version

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Publish Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages

    - name: Show Allure Report URL
      if: always()
      run: echo "Allure Report deployed https://tijothomas95.github.io/PytestPlaywrightAutomation/"
